### ISSUE TITLE
All periphery rules should include units

### ISSUE THREAD

**Issue by mithro** [google/skywater-pdk#105]
All the periphery rules in the documentation should include units.

**Comment by pkatarzynski** [comment]
Judging from the CSV files located here https://github.com/google/skywater-pdk/tree/master/docs/rules/periphery a numeric value associated with a certain rule has one unit ( [um] I presume) unless specified differently in the rule description. There is no coherent formating for the units - they are expressed like mm [mm] (mm). 
I think we can parse the rule text, look for those units and assign them to the associated value as long as there is only one unit-like string detected.

**Comment by pkatarzynski** [comment]
Well there are rules which do not follow this pattern. Is there a chance we can introduce a "unit" column in the source CSV files?
We can populate it with a script which will do the unit searching as described above. Some of the missing units will need to be added manually but it looks like a single-pass process.

**Comment by pkatarzynski** [comment]
@mithro

**Comment by mithro** [comment]
@pkatarzynski Introducing a "unit" column in the source CSV file seems like a good idea.

**Comment by mithro** [comment]
We should also clean up how they are expressed.
