### ISSUE TITLE
Link to LICENSE on skywater-pdk.readthedocs.io

### ISSUE THREAD

**Issue by mguthaus** [google/skywater-pdk#118]
## Expected Behavior

The LICENSE should be clearly displayed at the bottom of the documentation pages at skywater-pdk.readthedocs.io. 

## Actual Behavior
Right now, it is unclear if the documentation is the same license as the GitHub repo since it is at a different domain.

## Steps to Reproduce the Problem

1. Go to https://skywater-pdk.readthedocs.io/
1. Seach for LICENSE

## Specifications

- Version: All
- Platform: N/A

**Comment by mithro** [comment]
@mguthaus - Logged a bug https://github.com/SymbiFlow/sphinx_symbiflow_theme/issues/30 on the [upstream sphinx_symbiflow_theme](https://github.com/SymbiFlow/sphinx_symbiflow_theme) to add support for displaying the license information easily.
