### ISSUE TITLE
Remove SOURCE USER ; from LEF

### ISSUE THREAD

**Issue by msaligane** [google/skywater-pdk#119]
## Expected Behavior
Please remove the SOURCE line from the current libraries LEF files.

## Actual Behavior
This syntax is not compatible with the LEF 5.6 syntax:
```
MACRO sky130_fd_sc_hd__o211a_4
  CLASS CORE ;
  **SOURCE USER ;**
```

**Comment by mithro** [comment]
This should be done in the next push.

**Comment by msaligane** [comment]
I verified a few LEF files and this seems to be done.

**Comment by mithro** [comment]
This was done to the upstream libraries at https://github.com/google/skywater-pdk/pull/123
