### ISSUE TITLE
remove  NAMESCASESENSITIVE ON ; from the LEF files

### ISSUE THREAD

**Issue by msaligane** [google/skywater-pdk#120]
## Expected Behavior

Please remove that line from the LEF files.

## Actual Behavior
This syntax is obsolete in LEF 5.6 syntax
`NAMESCASESENSITIVE ON ;
`

**Comment by mithro** [comment]
FYI @RTimothyEdwards

**Comment by RTimothyEdwards** [comment]
@mithro :  I just pushed a fix for magic.

**Comment by msaligane** [comment]
@RTimothyEdwards Sorry I don't know where the push is?

**Comment by mithro** [comment]
I will do this update.
