### ISSUE TITLE
Change the FILL cells class

### ISSUE THREAD

**Issue by msaligane** [google/skywater-pdk#129]
## Expected Behavior

Fill cells class should be defined as CORE SPACER
```
MACRO sky130_fd_sc_hd__fill_4
  CLASS CORE SPACER ;
  SOURCE USER ;
```
## Actual Behavior
Fill cells are defined as CLASS CORE 
```
MACRO sky130_fd_sc_hd__fill_4
  CLASS CORE ;
  SOURCE USER ;
```

**Comment by mithro** [comment]
@msaligane - I have added a fix for this, will be in the next skywater-pdk modules fix.
