### ISSUE TITLE
Unable to access the announcement google group

### ISSUE THREAD

**Issue by kkiningh** [google/skywater-pdk#17]
I'm unable to join the announcement Google group for this project (https://groups.google.com/forum/#!forum/skywater-pdk-announce gives a permission denied error), but I'd love to sign up for updates! Please let me know if there's anyway to join.

**Comment by mithro** [comment]
Permission on the list should be fixed now. Can you please take a look?

**Comment by kkiningh** [comment]
I can confirm that its fixed - just joined! Thanks!
