### ISSUE TITLE
README file:  "join link" for users is pointing to announce, not users

### ISSUE THREAD

**Issue by RTimothyEdwards** [google/skywater-pdk#18]
@mithro :  Halfway down the README file, there is a link to the "users" group, followed by a link to "join", but the "join" link is pointing to the "announce" group, not the "users" group.

**Comment by itviewer** [comment]
Is seems that the "users" group unable to join

**Comment by mithro** [comment]
@itviewer - I believe I have fixed the permissions, please try again now.
