### ISSUE TITLE
netgen setup property circuit specification bug

### ISSUE THREAD

**Issue by d-m-bailey** [google/skywater-pdk#201]
## Expected Behavior
property statements should reference circuit being processed

## Actual Behavior
property statements reference the other circuit

## Steps to Reproduce the Problem

1. fails when doing x-device comparison, but problem can be seen by examining the code.

Example:
```
    if {[lsearch $cells2 $dev] >= 0} {
        permute "-circuit2 $dev" 1 2
        property "-circuit1 $dev" series enable
        property "-circuit1 $dev" series {w critical}
        property "-circuit1 $dev" series {l add}
```
`-circuit1 `should be `-circuit2 `here.

## Specifications

- Version:
- Platform:

**Comment by mithro** [comment]
Which file is this found in?

**Comment by mithro** [comment]
I can't see anything like this in the PDK -> https://cs.opensource.google/search?q=circuit1&sq=&ss=skywater-pdk

**Comment by d-m-bailey** [comment]
Sorry, I was trying to figure out how to create a pull request to fix it. There are several other similar errors in the file.
 
sky130/netgen/sky130_setup.tcl

**Comment by d-m-bailey** [comment]
wrong github. should be in open_pdks. 

sorry again.
