### ISSUE TITLE
Availability of small ROM

### ISSUE THREAD

**Issue by PPlinux** [google/skywater-pdk#27]
For mine application specific device I need a small ROM e.g. 256Word 16bit.
I have already seen RAM and Flash announcement but will there also ROM available ?
Is there already some information about the specifaction (size, power, ..) and how to
use availble Flash as a ROM and programming it with minimal I/O interface ?
Hoping to receive a positive reaction, I meanwhile remain,

Patrick Pelgrims

**Comment by mguthaus** [comment]
Hi Patrick,

I also answered your question on the OpenRAM project. We do not support ROMs, but this would be a great project using the OpenRAM infrastructure. This is on the wish list and contributions are welcome.

Matt
