### ISSUE TITLE
sky130_fd_pr and sky130_fd_io submodules not updated

### ISSUE THREAD

**Issue by mguthaus** [google/skywater-pdk#321]
## Expected Behavior

When you clone the repo and run make submodules it should pull all the submodules. 

## Actual Behavior

It pulls all of them except for sky130_fd_pr and sky130_fd_io. In addition, it you manually pull, say, sky130_fd_pr, it cannot pull the latest tag which doesn't exist.

## Steps to Reproduce the Problem

1. `git clone git@github.com:google/skywater-pdk.git`
2. `SUBMODULE_VERSION=latest make submodules -j3 ||  make submodules -j1`
3. `git submodule update --init libraries/sky130_fd_pr`
4. `cd libraries/sky130_fd_pr/latest`
5. `git checkout main`

## Specifications

- Version: bb2f842ac8d1b750677ca25bc71fb312859edb82
- Platform: All

**Comment by mithro** [comment]
@mguthaus - Can you give the change in #323 a go?
