### ISSUE TITLE
 Layout for the SONOS shrunken cell in sky 130

### ISSUE THREAD

**Issue by ratul619** [google/skywater-pdk#342]
Hi , 

Where can i find layout for the SONOS shrunken cell ? 
I am trying to instantiate the same in klayout . But not able to find. The spice models are there it seems

Thanks in advance

**Comment by RTimothyEdwards** [comment]
There is no pre-defined layout for the SONOS cell.  It is essentially just like any other nMOS transistor, but with a SONOS implant layer, and it has to be over deep nwell.  In magic, there is a device generator for it, just a "Device type" selection in the nMOS device generator.

**Comment by RTimothyEdwards** [comment]
There is also no library of support circuitry for the SONOS programming, unfortunately.

**Comment by ratul619** [comment]
Thanks !

**Comment by ratul619** [comment]
Closing
