### ISSUE TITLE
Collaterals for ReRaM

### ISSUE THREAD

**Issue by ratul619** [google/skywater-pdk#344]
Hi ,

Please let know where to find the collaterals for ReRAM ? I believe that is supported for MPW4
 

Thanks

**Comment by QuantamHD** [comment]
The collateral is located in this repo, and will be included in this one soon. https://github.com/google/skywater-pdk-libs-sky130_fd_pr_reram

**Comment by ratul619** [comment]
Thanks for the quick response !
