### ISSUE TITLE
IO filler cell name ?

### ISSUE THREAD

**Issue by ratul619** [google/skywater-pdk#348]
Hi , 

Which cells is/are the IO filler cells? Not able to find in documentation , neither any candidate seems suitable in LEF . 

Thanks

**Comment by RTimothyEdwards** [comment]
Apparently you are not using the open_pdks installer [https://github.com/RTimothyEdwards/open_pdks] which is where the I/O filler cells are?

**Comment by ratul619** [comment]
I think i directly installed from the skywater-pdk git repo. I will look into the open_pdks . Thanks

**Comment by RTimothyEdwards** [comment]
Look in `sky130_ef_io.lef`. The fill cells are:

sky130_ef_io__com_bus_slice_1um
sky130_ef_io__com_bus_slice_5um
sky130_ef_io__com_bus_slice_10um
sky130_ef_io__com_bus_slice_20um

**Comment by ratul619** [comment]
Ah. Makes sense. I will have a look at those . Thanks @RTimothyEdwards
