### ISSUE TITLE
Wrong diode model names

### ISSUE THREAD

**Issue by FatsieFS** [google/skywater-pdk#352]
The documentation of the diodes on the Skywater PDK website (https://skywater-pdk--136.org.readthedocs.build/en/136/rules/device-details.html#diodes) is not right. The model names there don't match the actual spice model names.

**Comment by proppy** [comment]
Looking at https://skywater-pdk.readthedocs.io/en/main/rules/device-details.html#diodes

The name seems to match now:
```
sky130_fd_pr__diode_pw2nd_05v5
```
→ https://github.com/google/skywater-pdk-libs-sky130_fd_pr/blob/f62031a1be9aefe902d6d54cddd6f59b57627436/cells/diode_pw2nd_05v5/sky130_fd_pr__diode_pw2nd_05v5.model.spice

```
.model sky130_fd_pr__diode_pw2nd_05v5 d
```

Feel free to re-open by commenting on this issue if you find other discrepancies.
