### ISSUE TITLE
QRC tech file / captable

### ISSUE THREAD

**Issue by WahidSadiq** [google/skywater-pdk#354]
I am trying to implement this PDK in genus and innovus. For mmmc we need captable or qrc tech file. But i didn't find it. is there any way to get it?

**Comment by QuantamHD** [comment]
This PDK is mostly targeted at the opensource eda tools, and we have limited support for commercial EDA tools.

It should be possible to create those files from the existing data in this repo. We would happily accept pull requests to enhance the PDK in that direction.

@RTimothyEdwards do you have any insight on these specific files?

**Comment by WahidSadiq** [comment]
thanks man. it will be very helpful to get the data related to QRC tech file so that we can create it

**Comment by rovinski** [comment]
Maybe take a look at #185 and #187. That might help get you started.

**Comment by WahidSadiq** [comment]
> Maybe take a look at #185 and #187. That might help get you started.

thanks @rovinski i think this is enough to get myself started
