### ISSUE TITLE
Issue in make timing step while installing the skywater-pdk

### ISSUE THREAD

**Issue by vsooden** [google/skywater-pdk#364]
I am trying to install skywater-pdk by following the steps provided on open_pdk website. 
During "make timing" I am getting the following error message. I would appreciate it if you could help me to resolve it. 

pi@raspberry:~/skywater-pdk $ make timing
chmod a+x /home/pi/skywater-pdk/env/downloads/Miniconda3-latest-Linux-x86_64.sh
/home/pi/skywater-pdk/env/downloads/Miniconda3-latest-Linux-x86_64.sh -p /home/pi/skywater-pdk/env/conda -b -f
PREFIX=/home/pi/skywater-pdk/env/conda
Unpacking payload ...
/home/pi/skywater-pdk/env/downloads/Miniconda3-latest-Linux-x86_64.sh: 416: /home/pi/skywater-pdk/env/downloads/Miniconda3-latest-Linux-x86_64.sh: /home/pi/skywater-pdk/env/conda/conda.exe: not found
/home/pi/skywater-pdk/env/downloads/Miniconda3-latest-Linux-x86_64.sh: 418: /home/pi/skywater-pdk/env/downloads/Miniconda3-latest-Linux-x86_64.sh: /home/pi/skywater-pdk/env/conda/conda.exe: not found
make: *** [/home/pi/skywater-pdk/third_party/make-env/conda.mk:128: /home/pi/skywater-pdk/env/conda/bin/python] Error 1
 

Thanks

**Comment by mithro** [comment]
Running `make timing` on a RPi is going to take a *very* long time -- probably days at the moment?

**Comment by proppy** [comment]
@vsooden There are conda packages for open_pdks which should install file on a raspberry pi (since they are tagged noarch) and save you the long and tedious tasks to build the timing: https://anaconda.org/LiteX-Hub/open_pdks.sky130a

Feel free to re-open by commenting on this issue if it doesn't work for you.
