### ISSUE TITLE
An invalid attribute 'related_ground_pin' is found

### ISSUE THREAD

**Issue by RanChenRivai** [google/skywater-pdk#391]
## Expected Behavior
I want to convert .lib file to .db file for DC by Synopsys Library Complier.

## Actual Behavior
However，when Library Complier reads sky130_fd_sc_hd__ff_100C_1v65.lib, it reports multiple errors similar to the one below.

------------------------------------------
Error: Line 57389, Cell 'sky130_fd_sc_hd__dlclkp_1', pin 'M0', An invalid attribute 'related_ground_pin' is found. (LBDB-27)
------------------------------------------

In line 57389:
------------------------------------------
57386        pin ("M0") {
57387            direction : "internal";
57388            internal_node : "M0";
57389            related_ground_pin : "VNB";
57390            related_power_pin : "VPWR";
57391        }
57392        statetable ("CLK GATE","M0") {
57393            table : "L L : - : L,L H : - : H,H - : - : N";
57394        }
------------------------------------------

How do I fix this type of error?

**Comment by proppy** [comment]
Looks similar to what was discussed in #183, can you post a comment there instead?
