### ISSUE TITLE
90nm

### ISSUE THREAD

**Issue by quantrpeter** [google/skywater-pdk#393]
Hi
   Does skywater provide commercial 45nm or 90nm pdk?
thanks

**Comment by QuantamHD** [comment]
We'll be open sourcing their 90nm fdsoi process in the next few months

**Comment by mithro** [comment]
The open source 90nm technology was announced at https://opensource.googleblog.com/2022/07/SkyWater-and-Google-expand-open-source-program-to-new-90nm-technology.html

When released the PDK will be found at https://github.com/google/sky90fd-pdk

You can join the mailing list @ https://groups.google.com/forum/#!forum/sky90fd-pdk-announce to be notified when the PDK is available for usage.
