### ISSUE TITLE
Getting access to the Google Skywater PDK group

### ISSUE THREAD

**Issue by ChrisZonghaoLi** [google/skywater-pdk#396]
Greetings,

I just would like to know how to get into the Google group for this open-source PDK. I tried to open the link here ([foss-eda-tools.googlesource.com/skywater-pdk](https://foss-eda-tools.googlesource.com/skywater-pdk/)) and login with my Google account but it says my permission is denied with my current account. Any idea?

Thanks,

Chris

**Comment by mithro** [comment]
I have fixed the permission issue.

The repository at https://foss-eda-tools.googlesource.com/skywater-pdk/ is just a (read only) mirror of this repository at GitHub.
