### ISSUE TITLE
Segmentation fault while opening Magic VLSI with sky130 technology

### ISSUE THREAD

**Issue by ddm2000** [google/skywater-pdk#397]
What can I do to resolve this issue?

**Comment by RTimothyEdwards** [comment]
For one, you can provide enough information that somebody like me can diagnose the issue.  "segmentation fault while opening magic" is not actionable information.

**Comment by pgielda** [comment]
Looking quickly at the logs seems that "make install" step failed. It says that your filesystem is read-only.

**Comment by RTimothyEdwards** [comment]
I think you have more than one issue here.  The most problematic issue is that your version of magic is very old.  That is probably what is causing the error with `make`, although it would be necessary to look through the log file to figure out where the actual error is being reported.  Secondly, the `OSError ...  Read-only file system` message is a bit concerning, and probably has something to do with the VM;  do you really have sudo privileges within the VM?  Lastly, you should not use the source template file `sky130.tech` on the command line to magic.  This is a template file and not an actual tech file.

**Comment by proppy** [comment]
@ddm2000 if you want to install the latest version of magic without building is from source, you could give a try to the conda package published here: https://anaconda.org/conda-forge/magic
