### ISSUE TITLE
Cadence genus

### ISSUE THREAD

**Issue by quantrpeter** [google/skywater-pdk#409]
Dear all
    After i clone the repo, how can i build the .lib file for Cadence genus?
thanks
Peter

**Comment by quantrpeter** [comment]
any hints?

![image](https://user-images.githubusercontent.com/50471577/214799917-ce399aeb-c232-4e45-bc08-750aed2de22f.png)

**Comment by 12562** [comment]
Hi Peter, 
You can set the lib search path to the pdk as follows:
set_db init_lib_search_path <Path to PDK>/pdks/sky130A/libs.ref/sky130_fd_sc_hd/lib/
and then, read the liberty file using read_libs command as follows:
read_libs sky130_fd_sc_hd__tt_025C_1v80.lib 

Thanks,
Mohit

**Comment by quantrpeter** [comment]
Thank you Mr @12562
