### ISSUE TITLE
Error while installing skywater PDK during make install step

### ISSUE THREAD

**Issue by aakash-ics** [google/skywater-pdk#420]
![Error_Skywater](https://github.com/google/skywater-pdk/assets/85435384/bca31775-860b-4338-896e-5e90cc4deebd)

I am getting this error multiple times while installing skywater pdk

Kindly help.

Thanking you
Aakash Gupta

**Comment by strut-09** [comment]
Hey aakash,i got the same,how did you resolve this?

**Comment by aakash-ics** [comment]
Hi,

I saw the thread it had some posts by repo managers which I followed and
things worked but those posts no longer exists.

There was some file where this change regarding yosys was supposed to be
made.

Kindly ask Rtimothyedwards regarding this.

Thanks and regards
Aakash Gupta
