### ISSUE TITLE
where is gds of fet ? only rf_ ?

### ISSUE THREAD

**Issue by jalcim** [google/skywater-pdk#426]
## Expected Behavior
gds of all FET device

## Actual Behavior
only gds of rf_
exemple :
here nothing
https://github.com/google/skywater-pdk-libs-sky130_fd_pr/tree/main/cells/nfet_01v8

here its provided
https://github.com/google/skywater-pdk-libs-sky130_fd_pr/blob/main/cells/rf_nfet_01v8/

Then ?
what its mean ?
why we have the spice of nfet but didn't have the gds for use it on openROAD ?

**Comment by RTimothyEdwards** [comment]
GDS is only provided for devices which have one and only one approved layout from the foundry.  That applies to the "RF" devices, each of which has its own device model corresponding to the exact layout.  All "regular" (non-RF) devices are expected to have layout generated from device generator scripts (in magic or klayout).
