### ISSUE TITLE
Who is maintaining "Conda EDA tools packages for Aarch64?

### ISSUE THREAD

**Issue by jun1okamura** [google/skywater-pdk#428]
Hi @proppy 

I am trying to install OpenEDA/PDK into my MAC M2 on Ubuntu(Aarch64) 22.04 by UTM (Version 4.2.5) but seems to me there are some missing packages. I can help compile those if I know the detailed procedures.

Jun

## Expected 
No error

## Actual Behavior
Error 

## Steps to Reproduce the Problem
> make timing

...

> Retrieving notices: ...working... done
Collecting package metadata (repodata.json): done
Solving environment: failed
> 
> ResolvePackageNotFound: 
>  - netlistsvg
>  - iverilog
>  - yosys
>
> make: *** [/home/okamura/PDK/skywater-pdk/third_party/make-env/conda.mk:145: /home/okamura/PDK/skywater-pdk/env/conda/envs/skywater-pdk-scripts/bin/python] Error 1
 
## Specifications

- Version: 
- Platform:
Ubuntu (Aarch64) 22.04 on MAC M2 by UTM (Version 4.2.5)

**Comment by proppy** [comment]
Can you file an issue against https://github.com/hdl/conda-eda instead?

Thanks in advance.
