### ISSUE TITLE
Color for links in the generated document index are totally unreadable

### ISSUE THREAD

**Issue by holvo** [google/skywater-pdk#49]
The text in 
https://skywater-pdk.readthedocs.io/en/latest/genindex.html is 
barely readable do to its color.

Would you mind to change it to something with more contrast to the white background?

**Comment by mithro** [comment]
Yes, that does look horrible!

**Comment by mithro** [comment]
I've [opened a bug](https://github.com/SymbiFlow/sphinx_symbiflow_theme/issues/24) on [the upstream sphinx theme](https://github.com/SymbiFlow/sphinx_symbiflow_theme) and hopefully @daniellimws who as been improving that theme will be able to help!

**Comment by mithro** [comment]
This has now been fixed thanks to @daniellimws fixing the theme upstream!
