### ISSUE TITLE
sky130_fd_sc_hvl : The 'clk_width' attribute, which expects values of string type

### ISSUE THREAD

**Issue by msaligane** [google/skywater-pdk#69]
## Actual Behavior
The following error happens when reading the libs in primetime:
```
Error: Line 36, The 'clk_width' attribute, which expects values of string type,
    is being supplied a value of floating-point type. (LBDB-53)
clk_width : 2.500000e-08;
```

## Expected Behavior
To fix this issue:
clk_width should be defined this way:
` clk_width : "2.500000e-08";
`

**Comment by mithro** [comment]
@msaligane -- Wow, that is kind of stupid....

**Comment by mithro** [comment]
@msaligane - This affects the liberty files for all the digital cells, right?

**Comment by msaligane** [comment]
@mithro I only see this in the hvl library (maybe because the corners are different) but yes for the digital cells.
