### ISSUE TITLE
Periphery rules diagrams are referencing rules not in text

### ISSUE THREAD

**Issue by riking** [google/skywater-pdk#75]
## Expected Behavior
All rule numbers referenced in diagrams are present in the document.

## Actual Behavior
Several rule sections have the final rule cut off.

E.g. the photodiode section only goes up to `photo.10` but the image references `photo.11`

https://skywater-pdk.readthedocs.io/en/latest/rules/periphery.html#photo

https://skywater-pdk.readthedocs.io/en/latest/_images/p031-photo_dotdash.svg

**Comment by mithro** [comment]
Thanks for the report! I will investigate. If you have time, it would be super useful if you could provide a list of these missing rule numbers that you have found.

**Comment by RTimothyEdwards** [comment]
@mithro :  I can confirm that this is nearly ubiquitous.  Just checking the first ten or so rules, I think only one of them was not missing the last rule.  For example, these rules that are in the original SkyWater DRC PDF document are missing:  dnwell:7, pwbm:5, pwdem:6, hvtp:6, hvtr:3, lvtn:14, ncm:8.  So it is clearly a bug in the script that is losing the last line of nearly every rule set.

**Comment by mithro** [comment]
Probably cause by the https://github.com/google/skywater-pdk/blob/master/docs/rules/periphery/periphery-split-csv.py script then?

**Comment by mithro** [comment]
Looks like the csv file is also missing the last line? https://github.com/google/skywater-pdk/blob/master/docs/rules/periphery/p031-photo_dotdash.csv

**Comment by mithro** [comment]
Does look like that rule is in the base csv file @ https://github.com/google/skywater-pdk/blob/master/docs/rules/periphery/periphery.csv#L541 -- so the `periphery-split-csv.py` script is most definately the issue.
