### ISSUE TITLE
Publish script which recombined the individual cell liberty files into a single liberty library

### ISSUE THREAD

**Issue by mithro** [google/skywater-pdk#8]
The skywater-pdk publishes files split into individual cells and models. This makes it easier to see what is available but produces a large number of files and directories and these large number of files makes a number of tools unhappy.

The skywater-pdk repository has Python scripts to combined cells and models inside a library into a single file to make it easier to use with these tools.

This script will be published at a later date.

**Comment by mithro** [comment]
This should include documentation on how to run and use these scripts.

**Comment by thesourcerer8** [comment]
libertymerge is already capable of doing that: https://codeberg.org/tok/librecell/src/branch/master/librecell-lib should I provide documentation for it?
