### ISSUE TITLE
re-opening [#77](https://github.com/google/skywater-pdk/issues/77) [Blocking the OpenLane release]

### ISSUE THREAD

**Issue by agorararmard** [google/skywater-pdk#93]
**This is blocking the OpenLane release**
[#77 ](https://github.com/google/skywater-pdk/issues/77)
## Follow-up comment:

 I just pulled and did git submodule update --init and ran make sky130_fd_sc_hs. I found that the issue still exists in all three versions (latest, v0.0.1, v0.0.2). so to reiterate on what's the problem:

1- we have one json description for the typical hs library with 25C and 1.80V: sky130_fd_sc_hs__tt_025C_1v80_ccsnoise.lib.json
2- However, two liberties are generated: sky130_fd_sc_hs__tt_025C_1v80_ccsnoise.lib and sky130_fd_sc_hs__tt_025C_1v80.lib.
3- We at efabless, openLane team, are only interested in this one sky130_fd_sc_hs__tt_025C_1v80.lib
4- Because yosys+ABC doesn't know how to parse ccsnoise information from liberty, and that's why we expect the file that doesn't contain the _ccsnoise postfix not to contain any ccsnoice information. Thus, the flow fails at synthesis.

I can share with you a small design so you can run against yosys and validate it from your side.

**Comment by mithro** [comment]
Duplicate #77
