### ISSUE TITLE
Mismatch between .lef and .lib files around bias pins (VNB and VPB)

### ISSUE THREAD

**Issue by mithro** [google/skywater-pdk#95]
@msaligane -- Can you add the description here?

**Comment by msaligane** [comment]
## Expected Behavior
No ports mismatch between LEF and LIB files.
   - Remove VNB and VPB from the liberty files will fix this issue.
   - Buffer/delay/inverter footprints are recognized.

## Actual Behavior

innovus/15.21.000 can only detect buffers and inverters when there is an exact match between LEF and lib files (IE if vpb/vnb are deleted from the .lib it works)
innovus/18.10.000 can detect buffers and inverters if vpb/vnb are defined in lower case or deleted.. but fails to detect them if they are defined as upper case.
Innovus uses its "footprintless" flow except if we provide a footprint file (unusual). And if there are mismatches between .libs and .lefs then innovus fails to recognize delay/buffer/inverter cells.

**Comment by msaligane** [comment]
I will close the issue I logged.

**Comment by mithro** [comment]
@msaligane Can you list the cells where they don't match?

**Comment by msaligane** [comment]
@mithro all of them actually.

**Comment by 20Mhz** [comment]
how about adding libertarian attribute physical_connection: device_layer? would that help? Semantic seems to imply the actual connection is outside

**Comment by rovinski** [comment]
I agree with @20Mhz. The right solution looks to be properly annotating the connections. Here is a sample of what this might look like:
```
pg_pin (VNB) {
  pg_type : nwell;
  physical_connection : device_layer;
  voltage_name : "VNB";
}
pg_pin (VPB) {
  pg_type : pwell;
  physical_connection : device_layer;
  voltage_name : "VPB";
}
pg_pin (VPWR) {
  pg_type : primary_power;
  related_bias_pin : "VNB";
  voltage_name : "VPWR";
}
pg_pin (VGND) {
  pg_type : primary_ground;
  related_bias_pin : "VPB";
  voltage_name : "VGND";
}
```
These pins should also be defined in the LEF on the nwell / pwell layers, if they aren't already.

**Comment by mithro** [comment]
I'm pretty sure we already have those?

**Comment by msaligane** [comment]
@mithro VPB/VNB aren't there in the lef files. Adn I do not think they can be defined. The connection to the wells is that through tap cells.

I have no preferences of deleting these pins from the .libs or adding in the lef. 
@rovinski there is no pin for nwell/pwell in any standard cell (the tap cell takes care of that)...
AFAIK, you only find that in fdsoi or ddc technologies.

**Comment by mithro** [comment]
Looking at https://foss-eda-tools.googlesource.com/skywater-pdk/libs/sky130_fd_sc_hd/+/refs/heads/master/cells/a2111o/sky130_fd_sc_hd__a2111o_1__ff_100C_1v65.lib.json#137
It seems like we should clean up the definition to match what @rovinski suggested.

We can also add an output mode for the liberty generator to skip the bias pins.

I'm going to split this into two seperate GitHub issues.

**Comment by msaligane** [comment]
@mithro Sounds good. Let me know when it is available to test. The .lib modification should probably fix this issue (without changing the LEF files).

**Comment by rovinski** [comment]
@msaligane other commercial PDKs have pwells and nwells exposed as pins in the LEF. Having a LEF pin exposed does not imply anything about connectivity from the well to other parts of the cell. Tapcells have internal connections from the rails to the wells, but that doesn't mean that those are the only cells which should have well pins. I'm pretty sure if one wants to use any kind of biasing strategy, you need those pins exposed.

**Comment by mithro** [comment]
I have split this into #97 and #98 and hence closing this issue.
